### ISSUE TITLE
Use common interface for exposed workflows of modules in the same category

### ISSUE THREAD

**Issue by emi80** [biocorecrg/BioNextflow#7]
Hi all,
as discussed during today's meeting, it might be good to use common interfaces for exposed workflows of modules belonging to the same category (e.g. `alignment`). 

For example, for a given module in the `alignment` category the interface could include `INDEX`, `MAP` and `ALIGN`. So, for the current [STAR](../blob/master/subworkflows/alignment/star.nf) module, one would rename the exposed workflows as follows:
- `STAR_INDEX` -> `INDEX`
- `STAR_INDEX_NOANNO` -> move to `INDEX` and use some logic or an optional input to use the same workflow with/without theannotation (if not really possible include `INDEX_NOANNO` to the interface)
- `STAR_MAP` -> `MAP`
- `STAR_ALL` -> `ALIGN`

Thoughts and comments are welcome!

Cheers

**Comment by lucacozzuto** [comment]
Hi Emilio!
Good idea. I'll work on it.

L

**Comment by lucacozzuto** [comment]
I changed the names. I don't put the choice of indexing with or without the annotation at the level of INDEX but later on (ALL)
